### PR TITLE
revival: revive the module for tarantool 1.10+

### LINKED ISSUE #9: Revive the module
Cloned the module and tried to build against tarantool-2.5.0-4-gd6d69c9fb.

```sh
$ git clone --recursive git@github.com:tarantool/migrate.git
$ cmake . -DCMAKE_BUILD_TYPE=RelWithDebInfo
$ make
```

Got the following error:

```
[ 87%] Building C object migrate/xlog/CMakeFiles/xlog.dir/xlog.c.o
/home/alex/p/tarantool-meta/migrate/migrate/xlog/xlog.c:258:1: error: array type has incomplete element type ‘struct luaL_reg’
  258 | parser_lib_func [] = {
      | ^~~~~~~~~~~~~~~
```

Fixed:

```diff
diff --git a/migrate/xlog/xlog.c b/migrate/xlog/xlog.c
index 8a3eaf6..831be13 100644
--- a/migrate/xlog/xlog.c
+++ b/migrate/xlog/xlog.c
@@ -254,7 +254,7 @@ lua_snap_pairs(struct lua_State *L)
        return 2;
 }
 
-static const struct luaL_reg
+static const struct luaL_Reg
 parser_lib_func [] = {
        { "snap_pairs",         lua_snap_pairs           },
        { "xlog_pairs",         lua_xlog_pairs           },
```

Successfully built the module, but with implicit declarations warnings from mpstream.c:

```
/home/alex/p/tarantool-meta/migrate/migrate/xlog/mpstream.c:279:15: warning: implicit declaration of function ‘mp_encode_ext’; did you mean ‘mp_encode_int’? [-Wimplicit-function-declaration]
  279 |   char *pos = mp_encode_ext(data, ext, len, type);
      |               ^~~~~~~~~~~~~
      |               mp_encode_int
```

Anyway, tried to run tests:

```
$ ctest -VV
<...>
1: LuajitError: ...ojects/tarantool-meta/migrate/test/migrate/xlog/init.lua:20: bad argument #1 to 'load' (string expected, got nil)
```

Fixed it this way (just for test, maybe it should be done in more accurate way, see the similar changes in the avro-schema module):

```diff
diff --git a/migrate/xlog/init.lua b/migrate/xlog/init.lua
index d074399..4d0b77e 100644
--- a/migrate/xlog/init.lua
+++ b/migrate/xlog/init.lua
@@ -17,7 +17,7 @@ local UINT64_MAX = 18446744073709551615ULL
 
 -- ffi.load(package.searchpath('migrate.xlog.libtarantool', package.cpath), true)
 -- ffi.load(package.searchpath('migrate.xlog.libtarantoolrpl', package.cpath), true)
-ffi.load(package.searchpath('migrate.xlog.internal', package.cpath), true)
+ffi.load(package.search('migrate.xlog.internal', package.cpath), true)
 
 local function man_gc(object)
     log.debug("GC'ed %s", tostring(object))
```

Got the error:

```sh
$ ctest -VV
<...>
1: LuajitError: ...ojects/tarantool-meta/migrate/test/migrate/xlog/init.lua:20: /home/alex/projects/tarantool-meta/migrate/test/migrate/xlog/internal.so: undefined symbol: CTID_CONST_STRUCT_TUPLE_REF
```

Made attempt to fix it:

```diff
diff --git a/migrate/xlog/tuple.c b/migrate/xlog/tuple.c
index 01eeabc..be04c29 100644
--- a/migrate/xlog/tuple.c
+++ b/migrate/xlog/tuple.c
@@ -16,7 +16,7 @@
 #include "mpstream.h"
 #include "xlog.h"
 
-extern uint32_t CTID_CONST_STRUCT_TUPLE_REF;
+extern uint32_t CTID_STRUCT_TUPLE_REF;
 extern struct ibuf xlog_ibuf;
 extern box_tuple_format_t *tuple_format;
 
@@ -31,12 +31,12 @@ mmpstream_tarantool_err(void *error_ctx, const char *err, size_t errlen)
 struct tuple *
 lua_istuple(struct lua_State *L, int narg)
 {
-       assert(CTID_CONST_STRUCT_TUPLE_REF != 0);
+       assert(CTID_STRUCT_TUPLE_REF != 0);
        uint32_t ctypeid;
        void *data;
 
        data = luaL_checkcdata(L, narg, &ctypeid);
-       if (ctypeid != CTID_CONST_STRUCT_TUPLE_REF)
+       if (ctypeid != CTID_STRUCT_TUPLE_REF)
                return NULL;
 
        return *(struct tuple **) data;
@@ -65,9 +65,9 @@ lua_tuple_gc(struct lua_State *L)
 static void
 lua_pushtuple(struct lua_State *L, struct tuple *tuple)
 {
-       assert(CTID_CONST_STRUCT_TUPLE_REF != 0);
+       assert(CTID_STRUCT_TUPLE_REF != 0);
        struct tuple **ptr = (struct tuple **)
-               luaL_pushcdata(L, CTID_CONST_STRUCT_TUPLE_REF);
+               luaL_pushcdata(L, CTID_STRUCT_TUPLE_REF);
        *ptr = tuple;
        /* The order is important - first reference tuple, next set gc */
        if (box_tuple_ref(tuple) != 0) {
```

It reflects [2.2.0-109-g077671fe0](https://github.com/tarantool/tarantool/commit/077671fe04b5fec898cccecd4aac12ee4281ce0b) tarantool commit. But anyway, we don't export CTID_STRUCT_TUPLE_REF symbol as well many other ones since [1.7.1-246-g4c4c1ccbe](https://github.com/tarantool/tarantool/commit/4c4c1ccbe422e1420ce0c0b36194fc61bb857ed4) (inclusive). There is relevant [issue](https://github.com/tarantool/tarantool/issues/2971) in tarantool.

Here I stuck.

### PR DESCRIPTION
**Pull request by LeonidVas**
The patch includes minimal changes to work correctly with
tarantool 1.10+.
The Indication of correctnesses of work is compilitaion, tests,
packages building.
More on some of the reasons for the changes:
* When installing msgpuck headers to "/usr/include" additional
  "msgpuck" directory is no longer used.
* The msgpuck is no longer header-only library.
* Since 1.7.6 (https://github.com/tarantool/tarantool/commit/f05254c9cc838dc94e218c2f064af411ac667350)
  it's easy to use package.search instead of package.searchpath.
  package.search have a wider range of searches.
* In "migrate/xlog/mpstream.c" some of the function arguments
  were mistaken.
* Since tarantool 1.7.5 the "luaT_pushtuple" function has been
  implemented for tarantool Lua/C API, which can be used instead of
  the "lua_pushtuple" from "migrate/xlog/tuple.c". Moreover, we
  can't use the "luaT_pushtuple" function from "migrate/xlog/tuple.c",
  because different tarantool versions use either CTID_CONST_STRUCT_TUPLE_REF
  or CTID_STRUCT_TUPLE_REF.
* "luaL_reg" is a deprecated alias for "luaL_Reg".
* The list of distributions for travis-ci contains already unsupported.
* The repository address "https://github.com/bigbes/migrate" is
  deprecated.
* After the "backward compatibility killer" feature, also famous as
  "unhide all symbols of tarantool", has been implemented, we should
  have up-to-date versions of the "small" and "msgpuck" libraries in
  modules.
  Additional Information: https://lists.tarantool.org/pipermail/tarantool-discussions/2020-September/000095.html

Fixes #9

Changelog: revive the module for tarantool 1.10+.

The "xdir_test" is flaky (sometimes reproduced on travis).
I think we should release before and after the patch.
Update PACKAGECLOUD_REPO from 1_6 to 1_10 for travis-ci.

### CODE REVIEW

File: debian/changelog [hunk 1]
```diff
@@ -1,5 +1,11 @@
...
+  * Reviving the module for tarantool 1.10+
+
+ -- Leonid Vasiliev <lvasiliev@tarantool.org>  Mon, 21 Sep 2020 11:30:00 +0300
+
 tarantool-migrate (0.0.1-1) unstable; urgency=low
 
   * Initial release
 
- -- Eugene Blikh <bigbes@tarantool.org>  Mon, 29 Feb 2016 11:30:00 +0300
+ -- Eugene Blikh <bigbes@tarantool.org>  Mon, 29 Feb 2016 11:30:00 +0300
```
Comment (Totktonada) [inline debian/changelog:11]: Nit: No newline symbol at end of the file.

File: migrate/xlog/mpstream.c [hunk 2]
```diff
@@ -276,7 +276,7 @@ mmpstream_encode_ext(struct mpstream *stream, const char *ext, uint32_t len,
 	assert(mp_sizeof_ext(len) < 5 + 1 + len);
 	char *data = mmpstream_reserve(stream, 1);
 	if (data) {
-		char *pos = mp_encode_ext(data, ext, len, type);
+		char *pos = mp_encode_ext(data, type, ext, len);
```
Comment (Totktonada) [inline migrate/xlog/mpstream.c:279]: Curious fact: The function was added to msgpuck in 2019, but this code is from 2016. The function is not used, though.

File: rpm/tarantool-migrate.spec [hunk 3]
```diff
@@ -34,5 +34,8 @@ make %{?_smp_mflags}
 %doc README.md
 
 %changelog
+* Mon Sep 21 2020 Leonid Vasiliev <lvasiliev@tarantool.org> 1.0.1-1
+- Reviving the module for tarantool 1.10+
+
 * Mon Feb 29 2016 Eugine Blikh <bigbes@tarantool.org> 1.0.0-1
-- Initial version of the RPM spec
+- Initial version of the RPM spec
```
Comment (Totktonada) [inline rpm/tarantool-migrate.spec:41]: Nit: No newline at end of the file.

**Review by Totktonada — APPROVED** [review]
LGTM.

File: debian/changelog (hunk 1 above)
Comment (LeonidVas) [reply debian/changelog]: Fixed.

File: migrate/xlog/mpstream.c (hunk 2 above)
Comment (LeonidVas) [reply migrate/xlog/mpstream.c:279]: LoL)

File: rpm/tarantool-migrate.spec (hunk 3 above)
Comment (LeonidVas) [reply rpm/tarantool-migrate.spec]: Fixed.
